### ISSUE TITLE
Context Not Found

### ISSUE THREAD

**Issue by vpapanchev** [w3c-ccg/vdl-vocab#6]
Hi,

The used json-ld context (https://w3id.org/vdl/v1) in the examples of the Unofficial Draft does not exist.
Last time I used it (2-3 months ago) it was fine, so I assume that it was moved somewhere else?
Can you provide the new location?

**Comment by davidlehn** [comment]
Fixed.  The target had an extension added here: https://github.com/w3c-ccg/vdl-vocab/pull/5.  The fix is here: https://github.com/perma-id/w3id.org/pull/3083.

**Comment by brianorwhatever** [comment]
This has been addressed and the context now resolves. Issue can be closed.
